name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rodar um script de build
        run: |
          echo "Compilando o projeto..."
          # Aqui você pode rodar um script como uma "função"

          on:
  push:
    branches: [main]
  workflow_dispatch:

