name: Gerar GIF de Atividade

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # a cada 1 hora
  workflow_dispatch:

jobs:
  generate-activity-gif:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar gráfico de atividade
        run: |
          curl -s https://raw.githubusercontent.com/Ashutosh00710/github-readme-activity-graph/master/activity-graph.php?username=Techi-fl&hide_border=true&theme=react-dark > activity-graph.gif

      - name: Commit e push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add activity-graph.gif
          git commit -m "Atualiza gráfico de atividade"
          git push
